# vim:ft=yaml.ansible
---
# tasks file for postgresql
- name: "Update packages"
  ansible.builtin.dnf:
    name: "*"
    update_only: true

- name: "Import GPG key from postgresql"
  ansible.builtin.rpm_key:
    state: "present"
    key: "https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG"

- name: "Disable default postgresql repo"
  ansible.builtin.copy:
    dest: /etc/dnf/modules.d/postgresql.module
    content: |
      [postgresql]
      name=postgresql
      stream=
      profiles=
      state=disabled
    mode: "0644"

- name: "Install postgreSQL 15 pgdg repo"
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: "present"

- name: "Install postgreSQL 15"
  ansible.builtin.dnf:
    name: "postgresql15-server"
    state: "present"

- name: "Install python3-pip"
  ansible.builtin.dnf:
    name: "python3-pip"
    state: "present"

- name: "Install python postgres adapter"
  ansible.builtin.pip:
    name: "psycopg2-binary"
    executable: "/usr/bin/pip3"
    version: 2.8.6
    state: "present"

- name: "Find out if PostgreSQL was initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/15/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  ansible.builtin.command: "postgresql-15-setup initdb"
  when: not postgres_data.stat.exists
  changed_when: false

- name: "Start and enable postgres service"
  ansible.builtin.service:
    name: "postgresql-15"
    state: "started"
    enabled: "yes"
