http:
  routers:
    app-blue-green:
      service: app-blue-green-svc
      rule: "Host(`api.prod.app.com`)"
  services:
    app-blue-green-svc:
      weighted:
        services:
          - name: app-blue@ecs
            weight: 20
          - name: app-green@ecs
            weight: 80
