---
tcp:
  routers:
    postgres:
      entryPoints:
        - postgres
      rule: HostSNI(`*`)
      service: postgres

  services:
    postgres:
      loadBalancer:
        servers:
          - address: "db-staging.cluster-cpjt2mlwyf5l.us-east-2.rds.amazonaws.com:5432"
