services:
  promtail:
    image: grafana/promtail
    deploy:
      mode: global
    ports:
      - 9080:9080
    command:
      - "-config.file=/etc/promtail/config.yaml"
    configs:
      - source: promtail
        target: /etc/promtail/config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

configs:
  promtail:
    file: ./promtail-config.yaml
