global:
  scrape_interval: 5s
  external_labels:
    monitor: "app-monitor"
rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] ## IP Address of the localhost
  - job_name: "ec2_aws_node_exporter_discovery"
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        filters:
          - name: tag:Name
            values:
              - ecs-prod
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        filters:
          - name: tag:Name
            values:
              - ecs-prod
  - job_name: "postgres_exporter"
    scheme: https
    static_configs:
      - targets: [pg-exporter.prod.app.com]
  - job_name: "nodejs_exporter"
    scheme: https
    static_configs:
      - targets: [blue.prod.app.com, green.prod.app.com]
