---
version: "3"
services:
  drone-runner:
    container_name: local-runner
    image: drone/drone-runner-docker:1
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
