version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    ports:
      - 4318
      - 9464
    configs:
      - source: otel-config
        target: /etc/otelcol-contrib/config.yaml
    networks:
      - o11y
  prometheus:
    image: prom/prometheus:latest
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.retention.time=3d",
        "--enable-feature=remote-write-receiver",
        "--query.lookback-delta=30s",
      ]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - prometheus:/prometheus
    ports:
      - 9090:9090
    deploy:
      placement:
        constraints:
          - node.hostname == node2
    networks:
      - o11y
  alertmanager:
    image: prom/alertmanager:v0.26.0
    configs:
      - source: alertmanager
        target: /etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - o11y
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=http://grafana.prod.app.gg
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.hostname == node2
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`grafana.prod.app.gg`)
        - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - o11y
      - log
      - web
  tempo:
    image: grafana/tempo
    ports:
      - 4317
      - 3200
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    configs:
      - source: tempo
        target: /etc/tempo/tempo.yaml
    networks:
      - o11y
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.10"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    command: ["--logtostderr=true", "--docker_only=true"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080
    networks:
      - o11y
configs:
  tempo:
    file: ./tempo.yaml
  otel-config:
    file: ./otel-collector-config.yaml
  alertmanager:
    file: ./alertmanager.yml
volumes:
  prometheus:
  grafana:
networks:
  o11y:
    external: true
  log:
    external: true
  web:
    external: true
