version: "3.9"
services:
  cloudflared:
    image: cloudflare/cloudflared
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
    env_file:
      - .env
