# vim:ft=yaml.ansible
- name: Add authorized key to perform operations
  hosts: swarm
  tasks:
    - name: Add the public key to the authorized_keys file
      ansible.posix.authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
