# vim:ft=yaml.ansible
---
- name: "Install PostgreSQL 15 on AlmaLinux/8, create user, and database"
  hosts: dbs
  become: true

  roles:
    - postgresql_install
    - {role: postgresql_bootstrap, become_user: postgres}
